name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: D016 Homework
      id: d016-homework
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 5
        setup-command: pip install pytest opencv-python-headless numpy
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        D016-HOMEWORK_RESULTS: "${{steps.d016-homework.outputs.result}}"
      with:
        runners: d016-homework
